/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtivarContaRouteImport } from './routes/ativar-conta'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated.vendas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated.produtos'
import { Route as AuthenticatedMinhaEmpresaRouteImport } from './routes/_authenticated.minha-empresa'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated.importar'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated.fornecedores'
import { Route as AuthenticatedFluxoCaixaRouteImport } from './routes/_authenticated.fluxo-caixa'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated.dre'
import { Route as AuthenticatedDespesasAnuaisRouteImport } from './routes/_authenticated.despesas-anuais'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCurvaAbcRouteImport } from './routes/_authenticated.curva-abc'
import { Route as AuthenticatedControleVendasRouteImport } from './routes/_authenticated.controle-vendas'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated.contas-receber'
import { Route as AuthenticatedContasPagarRouteImport } from './routes/_authenticated.contas-pagar'
import { Route as AuthenticatedContasBancariasRouteImport } from './routes/_authenticated.contas-bancarias'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated.compras'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated.categorias'
import { Route as AuthenticatedCartoesCreditoRouteImport } from './routes/_authenticated.cartoes-credito'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated.bi'
import { Route as AuthenticatedBalanceteRouteImport } from './routes/_authenticated.balancete'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as AuthCallbackRecoveryRouteImport } from './routes/auth/callback/recovery'
import { Route as ApiPublicRpcTestRouteImport } from './routes/api/public/rpc-test'
import { Route as ApiPublicAcceptInvitationRouteImport } from './routes/api/public/accept-invitation'
import { Route as AuthenticatedConfiguracoesCategoriasRouteImport } from './routes/_authenticated.configuracoes.categorias'
import { Route as AuthenticatedConfiguracoesAssinaturaRouteImport } from './routes/_authenticated.configuracoes.assinatura'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe.webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarContaRoute = AtivarContaRouteImport.update({
  id: '/ativar-conta',
  path: '/ativar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaEmpresaRoute =
  AuthenticatedMinhaEmpresaRouteImport.update({
    id: '/minha-empresa',
    path: '/minha-empresa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFluxoCaixaRoute = AuthenticatedFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDespesasAnuaisRoute =
  AuthenticatedDespesasAnuaisRouteImport.update({
    id: '/despesas-anuais',
    path: '/despesas-anuais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCurvaAbcRoute = AuthenticatedCurvaAbcRouteImport.update({
  id: '/curva-abc',
  path: '/curva-abc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControleVendasRoute =
  AuthenticatedControleVendasRouteImport.update({
    id: '/controle-vendas',
    path: '/controle-vendas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasPagarRoute =
  AuthenticatedContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContasBancariasRoute =
  AuthenticatedContasBancariasRouteImport.update({
    id: '/contas-bancarias',
    path: '/contas-bancarias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartoesCreditoRoute =
  AuthenticatedCartoesCreditoRouteImport.update({
    id: '/cartoes-credito',
    path: '/cartoes-credito',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBalanceteRoute = AuthenticatedBalanceteRouteImport.update({
  id: '/balancete',
  path: '/balancete',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRecoveryRoute = AuthCallbackRecoveryRouteImport.update({
  id: '/callback/recovery',
  path: '/callback/recovery',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicRpcTestRoute = ApiPublicRpcTestRouteImport.update({
  id: '/api/public/rpc-test',
  path: '/api/public/rpc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAcceptInvitationRoute =
  ApiPublicAcceptInvitationRouteImport.update({
    id: '/api/public/accept-invitation',
    path: '/api/public/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedConfiguracoesCategoriasRoute =
  AuthenticatedConfiguracoesCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesAssinaturaRoute =
  AuthenticatedConfiguracoesAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativar-conta': typeof AtivarContaRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/balancete': typeof AuthenticatedBalanceteRoute
  '/bi': typeof AuthenticatedBiRoute
  '/cartoes-credito': typeof AuthenticatedCartoesCreditoRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/controle-vendas': typeof AuthenticatedControleVendasRoute
  '/curva-abc': typeof AuthenticatedCurvaAbcRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas-anuais': typeof AuthenticatedDespesasAnuaisRoute
  '/dre': typeof AuthenticatedDreRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/configuracoes/assinatura': typeof AuthenticatedConfiguracoesAssinaturaRoute
  '/configuracoes/categorias': typeof AuthenticatedConfiguracoesCategoriasRoute
  '/api/public/accept-invitation': typeof ApiPublicAcceptInvitationRoute
  '/api/public/rpc-test': typeof ApiPublicRpcTestRoute
  '/auth/callback/recovery': typeof AuthCallbackRecoveryRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar-conta': typeof AtivarContaRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/balancete': typeof AuthenticatedBalanceteRoute
  '/bi': typeof AuthenticatedBiRoute
  '/cartoes-credito': typeof AuthenticatedCartoesCreditoRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/controle-vendas': typeof AuthenticatedControleVendasRoute
  '/curva-abc': typeof AuthenticatedCurvaAbcRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas-anuais': typeof AuthenticatedDespesasAnuaisRoute
  '/dre': typeof AuthenticatedDreRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/configuracoes/assinatura': typeof AuthenticatedConfiguracoesAssinaturaRoute
  '/configuracoes/categorias': typeof AuthenticatedConfiguracoesCategoriasRoute
  '/api/public/accept-invitation': typeof ApiPublicAcceptInvitationRoute
  '/api/public/rpc-test': typeof ApiPublicRpcTestRoute
  '/auth/callback/recovery': typeof AuthCallbackRecoveryRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ativar-conta': typeof AtivarContaRoute
  '/auth': typeof AuthRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/balancete': typeof AuthenticatedBalanceteRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/cartoes-credito': typeof AuthenticatedCartoesCreditoRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/contas-bancarias': typeof AuthenticatedContasBancariasRoute
  '/_authenticated/contas-pagar': typeof AuthenticatedContasPagarRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/controle-vendas': typeof AuthenticatedControleVendasRoute
  '/_authenticated/curva-abc': typeof AuthenticatedCurvaAbcRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/despesas-anuais': typeof AuthenticatedDespesasAnuaisRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fluxo-caixa': typeof AuthenticatedFluxoCaixaRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/configuracoes/assinatura': typeof AuthenticatedConfiguracoesAssinaturaRoute
  '/_authenticated/configuracoes/categorias': typeof AuthenticatedConfiguracoesCategoriasRoute
  '/api/public/accept-invitation': typeof ApiPublicAcceptInvitationRoute
  '/api/public/rpc-test': typeof ApiPublicRpcTestRoute
  '/auth/callback/recovery': typeof AuthCallbackRecoveryRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativar-conta'
    | '/auth'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/balancete'
    | '/bi'
    | '/cartoes-credito'
    | '/categorias'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/contas-bancarias'
    | '/contas-pagar'
    | '/contas-receber'
    | '/controle-vendas'
    | '/curva-abc'
    | '/dashboard'
    | '/despesas-anuais'
    | '/dre'
    | '/financeiro'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/importar'
    | '/minha-empresa'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/configuracoes/assinatura'
    | '/configuracoes/categorias'
    | '/api/public/accept-invitation'
    | '/api/public/rpc-test'
    | '/auth/callback/recovery'
    | '/auth/callback/'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar-conta'
    | '/auth'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/balancete'
    | '/bi'
    | '/cartoes-credito'
    | '/categorias'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/contas-bancarias'
    | '/contas-pagar'
    | '/contas-receber'
    | '/controle-vendas'
    | '/curva-abc'
    | '/dashboard'
    | '/despesas-anuais'
    | '/dre'
    | '/financeiro'
    | '/fluxo-caixa'
    | '/fornecedores'
    | '/importar'
    | '/minha-empresa'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/configuracoes/assinatura'
    | '/configuracoes/categorias'
    | '/api/public/accept-invitation'
    | '/api/public/rpc-test'
    | '/auth/callback/recovery'
    | '/auth/callback'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ativar-conta'
    | '/auth'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/_authenticated/balancete'
    | '/_authenticated/bi'
    | '/_authenticated/cartoes-credito'
    | '/_authenticated/categorias'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contas-bancarias'
    | '/_authenticated/contas-pagar'
    | '/_authenticated/contas-receber'
    | '/_authenticated/controle-vendas'
    | '/_authenticated/curva-abc'
    | '/_authenticated/dashboard'
    | '/_authenticated/despesas-anuais'
    | '/_authenticated/dre'
    | '/_authenticated/financeiro'
    | '/_authenticated/fluxo-caixa'
    | '/_authenticated/fornecedores'
    | '/_authenticated/importar'
    | '/_authenticated/minha-empresa'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/vendas'
    | '/_authenticated/configuracoes/assinatura'
    | '/_authenticated/configuracoes/categorias'
    | '/api/public/accept-invitation'
    | '/api/public/rpc-test'
    | '/auth/callback/recovery'
    | '/auth/callback/'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AtivarContaRoute: typeof AtivarContaRoute
  AuthRoute: typeof AuthRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicAcceptInvitationRoute: typeof ApiPublicAcceptInvitationRoute
  ApiPublicRpcTestRoute: typeof ApiPublicRpcTestRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar-conta': {
      id: '/ativar-conta'
      path: '/ativar-conta'
      fullPath: '/ativar-conta'
      preLoaderRoute: typeof AtivarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-empresa': {
      id: '/_authenticated/minha-empresa'
      path: '/minha-empresa'
      fullPath: '/minha-empresa'
      preLoaderRoute: typeof AuthenticatedMinhaEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fluxo-caixa': {
      id: '/_authenticated/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/despesas-anuais': {
      id: '/_authenticated/despesas-anuais'
      path: '/despesas-anuais'
      fullPath: '/despesas-anuais'
      preLoaderRoute: typeof AuthenticatedDespesasAnuaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/curva-abc': {
      id: '/_authenticated/curva-abc'
      path: '/curva-abc'
      fullPath: '/curva-abc'
      preLoaderRoute: typeof AuthenticatedCurvaAbcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/controle-vendas': {
      id: '/_authenticated/controle-vendas'
      path: '/controle-vendas'
      fullPath: '/controle-vendas'
      preLoaderRoute: typeof AuthenticatedControleVendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-pagar': {
      id: '/_authenticated/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/contas-pagar'
      preLoaderRoute: typeof AuthenticatedContasPagarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-bancarias': {
      id: '/_authenticated/contas-bancarias'
      path: '/contas-bancarias'
      fullPath: '/contas-bancarias'
      preLoaderRoute: typeof AuthenticatedContasBancariasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cartoes-credito': {
      id: '/_authenticated/cartoes-credito'
      path: '/cartoes-credito'
      fullPath: '/cartoes-credito'
      preLoaderRoute: typeof AuthenticatedCartoesCreditoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/balancete': {
      id: '/_authenticated/balancete'
      path: '/balancete'
      fullPath: '/balancete'
      preLoaderRoute: typeof AuthenticatedBalanceteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback/recovery': {
      id: '/auth/callback/recovery'
      path: '/callback/recovery'
      fullPath: '/auth/callback/recovery'
      preLoaderRoute: typeof AuthCallbackRecoveryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/rpc-test': {
      id: '/api/public/rpc-test'
      path: '/api/public/rpc-test'
      fullPath: '/api/public/rpc-test'
      preLoaderRoute: typeof ApiPublicRpcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/accept-invitation': {
      id: '/api/public/accept-invitation'
      path: '/api/public/accept-invitation'
      fullPath: '/api/public/accept-invitation'
      preLoaderRoute: typeof ApiPublicAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes/categorias': {
      id: '/_authenticated/configuracoes/categorias'
      path: '/categorias'
      fullPath: '/configuracoes/categorias'
      preLoaderRoute: typeof AuthenticatedConfiguracoesCategoriasRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/assinatura': {
      id: '/_authenticated/configuracoes/assinatura'
      path: '/assinatura'
      fullPath: '/configuracoes/assinatura'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAssinaturaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesAssinaturaRoute: typeof AuthenticatedConfiguracoesAssinaturaRoute
  AuthenticatedConfiguracoesCategoriasRoute: typeof AuthenticatedConfiguracoesCategoriasRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesAssinaturaRoute:
      AuthenticatedConfiguracoesAssinaturaRoute,
    AuthenticatedConfiguracoesCategoriasRoute:
      AuthenticatedConfiguracoesCategoriasRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBalanceteRoute: typeof AuthenticatedBalanceteRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedCartoesCreditoRoute: typeof AuthenticatedCartoesCreditoRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedContasBancariasRoute: typeof AuthenticatedContasBancariasRoute
  AuthenticatedContasPagarRoute: typeof AuthenticatedContasPagarRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedControleVendasRoute: typeof AuthenticatedControleVendasRoute
  AuthenticatedCurvaAbcRoute: typeof AuthenticatedCurvaAbcRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDespesasAnuaisRoute: typeof AuthenticatedDespesasAnuaisRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFluxoCaixaRoute: typeof AuthenticatedFluxoCaixaRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedMinhaEmpresaRoute: typeof AuthenticatedMinhaEmpresaRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBalanceteRoute: AuthenticatedBalanceteRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedCartoesCreditoRoute: AuthenticatedCartoesCreditoRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedContasBancariasRoute: AuthenticatedContasBancariasRoute,
  AuthenticatedContasPagarRoute: AuthenticatedContasPagarRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedControleVendasRoute: AuthenticatedControleVendasRoute,
  AuthenticatedCurvaAbcRoute: AuthenticatedCurvaAbcRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDespesasAnuaisRoute: AuthenticatedDespesasAnuaisRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFluxoCaixaRoute: AuthenticatedFluxoCaixaRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedMinhaEmpresaRoute: AuthenticatedMinhaEmpresaRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRecoveryRoute: typeof AuthCallbackRecoveryRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRecoveryRoute: AuthCallbackRecoveryRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AtivarContaRoute: AtivarContaRoute,
  AuthRoute: AuthRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicAcceptInvitationRoute: ApiPublicAcceptInvitationRoute,
  ApiPublicRpcTestRoute: ApiPublicRpcTestRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
