-- VEJAMAIS ERP — Blog Editorial V2
-- R9.3/R9.6/R9.7.1 — Publicador agendado seguro (repository-only)
-- NÃO aplicar ao staging/produção sem gate e autorização explícita.

begin;

alter table public.blog_workflow_events add column actor_source text not null default 'human';
alter table public.blog_workflow_events add constraint blog_workflow_events_actor_source_check check (actor_source in ('human','scheduler','system'));

create table blog_private.blog_scheduled_publication_attempts (
 id bigint generated by default as identity primary key,
 post_id uuid references public.blog_posts(id) on delete set null,
 post_slug text not null,
 revision_number integer not null,
 scheduled_at timestamptz,
 attempted_at timestamptz not null default now(),
 outcome text not null,
 error_code text,
 detail text,
 constraint blog_scheduled_publication_attempts_outcome_check check (outcome in ('published','skipped_no_approval','skipped_requirements','failed'))
);
create index blog_scheduled_publication_attempts_post_attempted_idx on blog_private.blog_scheduled_publication_attempts(post_id,attempted_at desc);
create index blog_scheduled_publication_attempts_outcome_attempted_idx on blog_private.blog_scheduled_publication_attempts(outcome,attempted_at desc);
create unique index blog_scheduled_publication_attempts_skip_once_uidx
 on blog_private.blog_scheduled_publication_attempts(post_id,revision_number,outcome,error_code)
 where outcome in ('skipped_no_approval','skipped_requirements');
revoke all on table blog_private.blog_scheduled_publication_attempts from public,anon,authenticated,service_role;

create or replace function blog_private.capture_blog_workflow_event()
returns trigger language plpgsql security definer set search_path=pg_catalog,public,blog_private,pg_temp as $$
declare _scheduler_context boolean:=current_setting('blog.scheduler_context',true)='scheduled_publisher'; _actor_user_id uuid; _actor_source text;
begin
 if _scheduler_context then _actor_user_id:=null; _actor_source:='scheduler'; else _actor_user_id:=coalesce(auth.uid(),new.updated_by,new.created_by); _actor_source:='human'; end if;
 if tg_op='INSERT' then insert into public.blog_workflow_events(post_id,from_status,to_status,actor_user_id,actor_source) values(new.id,null,new.status,_actor_user_id,_actor_source);
 elsif old.status is distinct from new.status then insert into public.blog_workflow_events(post_id,from_status,to_status,actor_user_id,actor_source) values(new.id,old.status,new.status,_actor_user_id,_actor_source); end if;
 return new;
end; $$;
revoke all on function blog_private.capture_blog_workflow_event() from public;

create or replace function blog_private.publish_due_scheduled_posts(p_limit integer default 50)
returns table(post_id uuid,outcome text,detail text,published_at timestamptz)
language plpgsql security definer set search_path=pg_catalog,public,blog_private,pg_temp as $$
declare _post record; _latest_review_decision text; _latest_reviewer uuid; _published_at timestamptz;
begin
 if p_limit is null or p_limit<1 or p_limit>500 then raise exception 'BLOG_SCHEDULED_PUBLISHER_LIMIT_INVALID'; end if;
 perform set_config('blog.scheduler_context','scheduled_publisher',true);
 for _post in select p.id,p.slug,p.revision_number,p.scheduled_at,p.category_id,p.author_id,p.meta_title,p.meta_description,p.content from public.blog_posts p where p.status='scheduled' and p.scheduled_at is not null and p.scheduled_at<=now() order by p.scheduled_at,p.id limit p_limit for update skip locked loop
  select r.decision,r.reviewer_user_id into _latest_review_decision,_latest_reviewer from public.blog_post_reviews r where r.post_id=_post.id and r.revision_number=_post.revision_number order by r.created_at desc,r.id desc limit 1;
  if _latest_review_decision is distinct from 'approved' or _latest_reviewer is null then
   -- Sem conflict-target: evita colisão entre nomes das colunas e variáveis OUT do PL/pgSQL.
   insert into blog_private.blog_scheduled_publication_attempts(post_id,post_slug,revision_number,scheduled_at,outcome,error_code,detail)
   values(_post.id,_post.slug,_post.revision_number,_post.scheduled_at,'skipped_no_approval','BLOG_CURRENT_REVISION_REQUIRES_APPROVAL','Revisão atual sem aprovação válida; nenhuma publicação executada.') on conflict do nothing;
   post_id:=_post.id; outcome:='skipped_no_approval'; detail:='BLOG_CURRENT_REVISION_REQUIRES_APPROVAL'; published_at:=null; return next; continue;
  end if;
  if _post.category_id is null or _post.author_id is null or nullif(btrim(coalesce(_post.meta_title,'')),'') is null or nullif(btrim(coalesce(_post.meta_description,'')),'') is null or jsonb_typeof(_post.content) is distinct from 'array' or jsonb_array_length(_post.content)=0 then
   insert into blog_private.blog_scheduled_publication_attempts(post_id,post_slug,revision_number,scheduled_at,outcome,error_code,detail)
   values(_post.id,_post.slug,_post.revision_number,_post.scheduled_at,'skipped_requirements','BLOG_PUBLISHING_REQUIREMENTS_NOT_MET','Requisitos editoriais de publicação não atendidos; nenhuma publicação executada.') on conflict do nothing;
   post_id:=_post.id; outcome:='skipped_requirements'; detail:='BLOG_PUBLISHING_REQUIREMENTS_NOT_MET'; published_at:=null; return next; continue;
  end if;
  begin
   update public.blog_posts p set status='published' where p.id=_post.id and p.status='scheduled' and p.scheduled_at is not null and p.scheduled_at<=now() returning p.published_at into _published_at;
   if not found then continue; end if;
   insert into blog_private.blog_scheduled_publication_attempts(post_id,post_slug,revision_number,scheduled_at,outcome,detail) values(_post.id,_post.slug,_post.revision_number,_post.scheduled_at,'published','Publicação agendada promovida de scheduled para published.');
   post_id:=_post.id; outcome:='published'; detail:=null; published_at:=_published_at; return next;
  exception when others then
   insert into blog_private.blog_scheduled_publication_attempts(post_id,post_slug,revision_number,scheduled_at,outcome,error_code,detail) values(_post.id,_post.slug,_post.revision_number,_post.scheduled_at,'failed',sqlstate,left(sqlerrm,1000));
   post_id:=_post.id; outcome:='failed'; detail:=sqlstate||': '||left(sqlerrm,900); published_at:=null; return next;
  end;
 end loop;
end; $$;
revoke all on function blog_private.publish_due_scheduled_posts(integer) from public,anon,authenticated,service_role;
comment on function blog_private.publish_due_scheduled_posts(integer) is 'R9 scheduled publisher. Private, idempotent due publication; deterministic skips deduplicated per post/revision/reason.';
commit;
