// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { env } from 'cloudflare:workers';
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const CANONICAL_SUPABASE_URL = 'https://hoalgniwydgydqaugqph.supabase.co';
const CANONICAL_SUPABASE_HOST = 'hoalgniwydgydqaugqph.supabase.co';

function readRuntimeString(name: string): string | undefined {
  const value = (env as unknown as Record<string, unknown>)[name];
  return typeof value === 'string' ? value.trim() : undefined;
}

function normalizeSecret(value: string): string {
  const trimmed = value.trim();
  if (
    trimmed.length >= 2 &&
    ((trimmed.startsWith('"') && trimmed.endsWith('"')) ||
      (trimmed.startsWith("'") && trimmed.endsWith("'")))
  ) {
    return trimmed.slice(1, -1).trim();
  }
  return trimmed;
}

function isRecognizedAdminKey(value: string): boolean {
  return value.startsWith('sb_secret_') || value.startsWith('eyJ');
}

function createSupabaseAdminClient() {
  const runtimeUrl = readRuntimeString('SUPABASE_URL');
  const rawServiceRoleKey = readRuntimeString('SUPABASE_SERVICE_ROLE_KEY');

  if (!rawServiceRoleKey) {
    throw new Error('Missing Cloudflare runtime secret: SUPABASE_SERVICE_ROLE_KEY');
  }

  if (runtimeUrl) {
    let runtimeHost: string;
    try {
      runtimeHost = new URL(runtimeUrl).host;
    } catch {
      throw new Error('Invalid Cloudflare runtime variable: SUPABASE_URL');
    }

    if (runtimeHost !== CANONICAL_SUPABASE_HOST) {
      throw new Error('Cloudflare SUPABASE_URL does not match the canonical VEJAMAIS Supabase project');
    }
  }

  const serviceRoleKey = normalizeSecret(rawServiceRoleKey);
  if (!isRecognizedAdminKey(serviceRoleKey)) {
    throw new Error('SUPABASE_SERVICE_ROLE_KEY is not a recognized administrative Supabase key format');
  }

  return createClient<Database>(CANONICAL_SUPABASE_URL, serviceRoleKey, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers:
//   const { getSupabaseAdmin } = await import("@/integrations/supabase/client.server");
//   const supabaseAdmin = getSupabaseAdmin();
export function getSupabaseAdmin() {
  if (!_supabaseAdmin) {
    _supabaseAdmin = createSupabaseAdminClient();
  }

  return _supabaseAdmin;
}
