// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function classifyServiceKey(value: string): 'MODERN_SECRET' | 'LEGACY_JWT' | 'OTHER' {
  if (value.startsWith('sb_secret_')) return 'MODERN_SECRET';
  if (value.startsWith('eyJ')) return 'LEGACY_JWT';
  return 'OTHER';
}

function safeHost(value: string): string {
  try {
    return new URL(value).host;
  } catch {
    return 'INVALID_URL';
  }
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const supabaseHost = safeHost(SUPABASE_URL);
  console.info('[VCRL-G2.16.2] Supabase runtime target fingerprint', {
    supabase_host: supabaseHost,
    service_key_present: true,
    service_key_format: classifyServiceKey(SUPABASE_SERVICE_ROLE_KEY),
  });

  const instrumentedFetch: typeof fetch = async (input, init) => {
    let requestHost = 'UNRESOLVED';
    try {
      const requestUrl = typeof input === 'string'
        ? input
        : input instanceof URL
          ? input.toString()
          : input.url;
      requestHost = new URL(requestUrl).host;
    } catch {
      requestHost = 'INVALID_URL';
    }

    console.info('[VCRL-G2.16.2] Supabase transport fetch started', {
      fetch_started: true,
      target_host: requestHost,
    });

    return fetch(input, init);
  };

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      fetch: instrumentedFetch,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS.
// SECURITY: Only use this for trusted server-side operations, never expose to client code.
// Load inside server handlers:
//   const { getSupabaseAdmin } = await import("@/integrations/supabase/client.server");
//   const supabaseAdmin = getSupabaseAdmin();
export function getSupabaseAdmin() {
  if (!_supabaseAdmin) {
    _supabaseAdmin = createSupabaseAdminClient();
  }

  return _supabaseAdmin;
}
